apiVersion: apps/v1
kind: Deployment

metadata:
  name: my-app-deployment

spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: docker.io/umairus/bb809204b95bb0513728a5e1ab8aab8e1d7ab7fa655be7d74d61014fb2c5f14f
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
